/*
  OBJETO ------------
  NAO SE UTILIZA O OPERADOR IGUAL PARA DECLARA OBJETOS. COMO PODEMOS VER NOS EXEMPLO ANTERIORES
  TODA DECLARACAO DE TIPO VEM APOS NOME DA VARIAVEL SEGUIDO DE EXE. LET VARIAVEL : TIPO E {} E
  A FORMA QUE DECLARAMOS OBJETOS.
*/
let carro : { modelo : string , ano : number } = {
    modelo : 'uno ' ,
    ano : 2006
};